In [7]:
import numpy as np
a = np.array([[-2, 7, -3], [4, -14, 6], [3, 7, 13]], dtype=float)
print(f'Матрица A:\n{a}\n')
print(f'Определитель:\n{np.linalg.det(a):.0f}')


Матрица A:
[[ -2.   7.  -3.]
 [  4. -14.   6.]
 [  3.   7.  13.]]

Определитель:
0


In [1]:
a = [[1,2,3], [1,1,1], [2,3,4]]
ra = np.linalg.matrix_rank(a)
print(ra)

2


In [2]:
a = [[0,0,2,1], [0,0,2,2],[0,0,4,3], [2,3,5,6]]
ra = np.linalg.matrix_rank(a)
print(ra)

3
